apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ .Values.pluginID }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessControl:
    trustDomain: "tkeel"
    {{- if (eq .Values.pluginID "keel") }}
    defaultAction: allow
    {{- else }}
    defaultAction: deny
    policies:
    - appId: rudder
      defaultAction: allow
      trustDomain: 'tkeel'
      namespace: {{ .Release.Namespace | quote }}
    - appId: keel
      defaultAction: allow
      trustDomain: 'tkeel'
      namespace: {{ .Release.Namespace | quote }}
    {{- end }}
  httpPipeline:
    handlers:
    - name: {{ .Values.pluginID }}-oauth2-client
      type: middleware.http.oauth2clientcredentials