# Default values for core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tkeelio/core
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"


nameOverride: ""
fullnameOverride: "core"

podAnnotations:
  dapr.io/enabled: "true"
  dapr.io/app-id: "core"
  dapr.io/app-port: "6789"
  dapr.io/app-protocol: "http"
  dapr.io/log-level: "debug"
  dapr.io/config: "core"

service:
  type: ClusterIP
  port: 6789


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  fullnameOverride: "core-mysql"
  auth:
    rootPassword: "zhu88jie"
    database: core
    username: "photoprism"
    password: "photoprism"

    initdbScripts:
      initdb.sql: |
        USE core;
        CREATE TABLE IF NOT EXISTS entity(
           id varchar(127) UNIQUE NOT NULL,
           user_id VARCHAR(63) NOT NULL,
           source VARCHAR(63) NOT NULL,
           tag VARCHAR(63),
           status VARCHAR(63),
           version INTEGER,
           entity_key VARCHAR(127),
           deleted_id VARCHAR(255),
           PRIMARY KEY ( id )
        )ENGINE=InnoDB DEFAULT CHARSET=utf8;
redis:
  nameOverride: "core-redis"
  fullnameOverride: "core-redis"
  architecture: standalone
