replicaCount: 1
pluginSecret: changeme
pluginPort: 8080

daprConfig: demo-echo

imagePullSecrets: ""

image:
  repository: tkeelio/demo-echo
  tag: 0.0.1
  pullPolicy: Always

tkeel-plugin-components:
  pluginID: demo-echo